version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app #where to store the artifacts
hooks:
  AfterInstall:
    - location: bin/deps.sh
      timeout: 100
      runas: ec2-user
  ApplicationStart:
    - location: bin/start.sh #start script for the website
      timeout: 100
      runas: ec2-user